### ISSUE TITLE
The vcpkg downloads  dependencies too slow

### ISSUE THREAD

**Issue by SYaoJun** [zz-jason/leanstore#100]
sometimes I need to add proxy tools or use VPN, so I think the vcpkg too hard for beginner.  is there some methods to replace it or some libs mirrors to accelerate the speed of download.

**Comment by zz-jason** [comment]
Most of the code is downloaded from github via curl, you can config `http_proxy` and `https_proxy` to speed up if necessary, ref: https://github.com/microsoft/vcpkg/issues/2350

**Comment by SYaoJun** [comment]
> Most of the code is downloaded from github via curl, you can config `http_proxy` and `https_proxy` to speed up if necessary, ref: [microsoft/vcpkg#2350](https://github.com/microsoft/vcpkg/issues/2350)
OK，I'll give it a try
