### ISSUE TITLE
docker环境似乎没有依赖的库，

### ISSUE THREAD

**Issue by SYaoJun** [zz-jason/leanstore#92]
CMake Error at CMakeLists.txt:73 (find_package):
  Could not find a package configuration file provided by "tabulate" with any
  of the following names:

    tabulateConfig.cmake
    tabulate-config.cmake

  Add the installation prefix of "tabulate" to CMAKE_PREFIX_PATH or set
  "tabulate_DIR" to a directory containing one of the above files.  If
  "tabulate" provides a separate development package or SDK, be sure it has
  been installed.

**Comment by zz-jason** [comment]
@SYaoJun Thanks All the third-party libraries should be installed by vcpkg inside the docker container. Could you share your build commands so I can help with this issue?

**Comment by SYaoJun** [comment]
I follow the steps of src/docker readme.md. Indeed, the reason of this problem is vcpkg not install. I solve this but another problem occur, how to deal with this bug? I run `make`
```
/tmp/ccVcYHjv.s: Assembler messages:
/tmp/ccVcYHjv.s:134757: Error: selected processor does not support `eor3 v0.16b,v1.16b,v3.16b,v0.16b'
/tmp/ccVcYHjv.s:134876: Error: selected processor does not support `eor3 v0.16b,v1.16b,v6.16b,v0.16b'
/tmp/ccpxzjde.s: Assembler messages:
/tmp/ccpxzjde.s:140327: Error: selected processor does not support `eor3 v0.16b,v1.16b,v3.16b,v0.16b'
/tmp/ccpxzjde.s:140446: Error: selected processor does not support `eor3 v0.16b,v1.16b,v6.16b,v0.16b'
make[2]: *** [src/CMakeFiles/leanstore.dir/build.make:118: src/CMakeFiles/leanstore.dir/btree/TransactionKV.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
```

**Comment by zz-jason** [comment]
@SYaoJun Did you build it on an arm chip? It's recommended to build on a x85 cpu.

**Comment by SYaoJun** [comment]
yes，I run docker on MacOS M1 chip.
